### ISSUE TITLE
Implement a JavaScript build system 

### ISSUE THREAD

**Issue by macumber** [ladybug-tools/spider-gbxml-tools#1]
Use JavaScript build tool to (NPM, Webpack, etc) generate a single minified JavaScript file which is run through Babel for backwards compatibility

@axelstudios might have input on best tools to use

**Comment by theo-armour** [comment]
@macumber 

Great first issue! more on this soon.

**Comment by theo-armour** [comment]
@macumber @axelstudios

My first protocol.json  for gbXML Viewer Basic is up:
https://github.com/ladybug-tools/spider-gbxml-tools/blob/master/gbxml-viewer-basic/package.json

The package-lock.json has been generated.

But when I look at my profile, no package has been generated:
https://www.npmjs.com/~ta

I'm sorry for being such a client-side derp here. I hope you can help.

**Comment by theo-armour** [comment]
@macumber @axelstudios

Yay! We have a gbXML Viewer NPM package!
 
https://www.npmjs.com/package/gbxml-viewer-basic

And it seems to work.

**Comment by theo-armour** [comment]
@macumber 

![image](https://user-images.githubusercontent.com/547626/43670634-d558bbfc-9742-11e8-9a3b-31ebdc055b63.png)

> Use JavaScript build tool to (NPM, Webpack, etc) generate a single minified JavaScript file which is run through Babel for backwards compatibility

## [fetch assemble save r2]( https://rawgit.com/ladybug-tools/spider-gbxml-tools/develop/fetch-assemble-save/r2/fetch-assemble-save.html )

## [Read Me]( https://github.com/ladybug-tools/spider-gbxml-tools/tree/develop/fetch-assemble-save )

* Buttons allow you to select various collections of assemblies
* Assembled text appears in a textarea element
* HTML files appear in an Iframe element

## To Do / Wish List

* Investigate and add all the OpenStudio requirements
* Needs lights
* Needs some modification to run Three.js releases older than r92
* Add link to source code
* Add dropdown with links to all Three.js releases
* Add strip out out multiple tabs and spaces feature

**Comment by mdengusiak** [comment]
we are moving to new code base.. in Maevia, 
...if we get contributor happy to make it Node.js compatible we will adjust code, 
I will tag as `Parked `so we can retrieve in the future
