### ISSUE TITLE
Update 2018-08-24 ~ gbXML to OpenStudio Report ~ Questions regarding 'seb.osm' to 'seb.xml'' 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#11]
@macumber 

The following is an excerpt from latest revision of  [gbXML to OpenStudio Report](  https://rawgit.com/ladybug-tools/spider-gbxml-tools/develop/#gbxml-to-openstudio-report.md )

This text documents the steps to convert an OSM file to a gbXML file that currently fails to complete an OpenStudio  simulation

The call to action: What text may be added to 'seb.xml' that will cause the run to complete successfully?

***

We want scripts that open gbXMl files and add sufficient data such that an OpenStudio Simulation may be created on the first pass without failure.

As a first step toward achieving this objective, there should be a body of gbXML files that are known to run simulations successfully.

A good place to start might be with the example file included with OpenStudio.

Upon a load of OpenStudio
* Open: openstudio-2.6.1\Examples\compact_osw\files\seb\files\seb.osm

Upon load of 'seb.osm' file:
* Note upgrade to new fille format
* Add EPW and DDY file URLs: OpenStudio > 'Site' tab
* Click: OpenStudio > 'Run Simulation' tab > 'Run' button
* Wait for simulation to complete

Upon successful completion of simulation run:
* Export data to gbXML file: OpenStudio > 'File' menu > 'Export' > 'gbXML'
* Save file as 'seb.xml' and place it in same folder as 'seb.osm'

Upon file save:
* Open new project: OpenStudio > 'File' menu > 'New'
* Import just saved 'seb.xml' file: OpenStudio > 'File' menu > 'Import' > 'gbXML'
* When prompted to save current project: click 'Discard'

Upon load of gbXML file:
* Add EPW and DDY file URLs: OpenStudio > 'Site' tab
* Click: OpenStudio > 'Run Simulation' tab > 'Run' button
* When prompted to save current project: save 'seb.osm' or 'seb-new.osm'
* Wait for simulation to complete
* Note the result that the run failed:

![image](https://user-images.githubusercontent.com/547626/44603499-beee7900-a797-11e8-92d9-c062f5605391.png)

This file details the errors: openstudio-2.6.1/Examples/compact_osw-2018-08-24/files/seb/run/eplusout.err

The question for the moment: What text may be added to 'seb.xml' that will cause the run to complete successfully?

**Comment by mostaphaRoudsari** [comment]
@theo-armour where can I find seb.osm on GitHub?

**Comment by mdengusiak** [comment]
continuation of https://github.com/ladybug-tools/spider-gbxml-tools/issues/10
