### ISSUE TITLE
Eye icon - hide element

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#14]
@theo-armour 

we had this nice icon with eye and is gone now... did you replace image to unicode again? we can revert this back?

![image](https://user-images.githubusercontent.com/14005893/47350834-ad99ee00-d6ae-11e8-901b-15bb604f5104.png)

aslo can we remove comma
thanks
![image](https://user-images.githubusercontent.com/14005893/47351063-200ace00-d6af-11e8-9803-c634975e9616.png)

**Comment by theo-armour** [comment]
> we had this nice icon with eye and is gone now... did you replace image to unicode again? we can revert this back?

No. This is a Windows 7 - ie 2009 - issue. Dev = future. Build = past.

> also can we remove comma

look at read me before reporting bugs

https://www.ladybug.tools/spider-gbxml-tools/#./cookbook/spider-gbxml-viewer-reports/README.md

**Comment by mdengusiak** [comment]
@theo-armour 
ok all clear now
