### ISSUE TITLE
Reviewing Surface Type Workflow 

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#15]
This workflow is for fixing only one problem: an exterior surface absents where it should be and presents where it should not. In a raw model there are many “exterior walls” inside the building. And there are blank spots where we want to see an exterior wall or roof. To fix such issues I would like to see the following app behavior:
1.	Visibility settings should be permanent during the session unless I change them: 
      • Make visible only the "exposed to sun" surface Types (external walls and roof) plus I want to see the Air surface type, because typically it represents a missing roof of external wall. Sure any set of surface types can be ON\OFF.
      • edges\surfaces visibility – I believe it should be a global setting not affected by level-by-level or space-by-space travelling. 
2.	I go from level to level and review the model quality. I expect only the categories I’ve made visible with the previous step appear on screen.
3.	Typically I change the following categories:
     •	Air -> Roof
     •	Air -> Exterior Wall
     • Exterior Wall -> Interior Wall.

I understand that my workflow is limited in surface Types. Because we are using the HAP software for calculations and it deals with the listed categories only. But anyways the described workflow should work for any scenario: just **“lock” the surface Types visibility and go through levels\spaces**. 

I believe the FZK viewer behaves similarly to the requested workflow and is a good example to refer to.

**Comment by theo-armour** [comment]
@EK-CEL 

A first pass at a response:

## [Spider gbXML Text Parser R8.0 'Evgeny' ]( https://www.ladybug.tools/spider-gbxml-tools/sandbox/spider-gbxml-text-parser/r8/spider-gbxml-text-parser-evgeny.html )

* Still many issues - particularly latency

**Comment by EvgenyK-SO** [comment]
Tried the first pass. Very nice. 

- It would be great to be able to to select multiple Levels. For example I want to review the podium so I need to select Levels 1, 2, and 3. To review a West Tower I select levels Level 6 West, Level 7 West, etc. To review the East Tower I select levels Level 6 East, Level 7 East, etc.
- It would be nice to have the <ALL LEVELS> item at the very first place in the list.
