### ISSUE TITLE
Spider gbXML Viewer Naming Rights

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#17]
After dialog with Michal, Mostapha and myself regarding the naming of projects, I remain confused,

Here's what people want:

Users want release numbers they can understand like R1, R2, R3 

Developers want descriptive names for what they are working on. For example, since moving on from Spider gbXML Viewer R14 'Aragog' there have been two huge coding forks: 

* Spider gbXML Viewer Basic R1 to R7.8
* Spider gbXML Text Parser R1 to R13
 
I could write for hours about this process, but let's not go there, Here is my current plan

Spider gbXML Viewer R15 'Maevia'

The first part indicates the next release of a product you know, The second code name 'Maevia' indicates a difference with 'Aragog'.

The bonus is that we get a cool looking spider:

![image](https://user-images.githubusercontent.com/547626/51969747-115c5180-242a-11e9-84eb-14a46a3d3ddb.png)

**Comment by mostaphaRoudsari** [comment]
IMO the key is being consistent and with the new approach both users and developers will be happy! 🚀

**Comment by EvgenyK-SO** [comment]
Sorry, English is not my first language and I should admit my vocabulary doesn't include words Aragog and Maevia. For the Spider tool the names do not help me to understand which of the species is newer. Usually I read the number and they work for me: 15 is newer (and better!) than 13. :)

**Comment by theo-armour** [comment]
@EK-CEL 

Not to worry there will be a release number for every future release.

There will also be a Latin spider species name as well. The reason is that some releases will be built on completely different code bases. Leading up to R15 there was a work on 'Spider gbXML Viewer Basic' R1 to R7 and 'Spider gbXML Viewer Text Parser' R1 to R13 ( and the parent of Spider gbXML Viewer R15 'Maevia') and well as other bits and pieces written in very different ways. The Latin names are to help you (and me) identify which fork came from where.  The code for 'Aragog' and 'Maevia' are very different. Any programmers looking at the source code will be very confused unless there is some kind of identification.

BTW, I don't think any of us speak Latin very well so we are all fairly equal. Any finding a good naming strategy when the code is still in a state of flux is always tricky.
