### ISSUE TITLE
Spider gbXML Viewer R15 'Maevia'

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#18]
@ladybug-tools/core @mdengusiak @EK-CEL

Spider gbXML Viewer R15 'Maevia' is kind of ready for testing. It does not yet have all the features of previous releases. Help deciding what features to bring in and with what priority is something you can help with now,

## [Spider gbXML Viewer R15 'Maevia' ]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer )

New features include

* handle very large files ( > 700MB )
* code is quite modular with code in small files

Use this link for the latest: http://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer
Source code: https://github.com/ladybug-tools/spider-gbxml-tools/tree/master/spider-gbxml-viewer

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Thank you for the update. The performance for large models is fantastic.
Some minor issues\comments\requests:

- It would be nice to have "toggle shadows" in the View Menu > Scene display settings.
- Keep the current state of the rotation when a storey is selected (or other tool is activated). Now the model starts rotating even it didn't before.
- Don't reset the current viewpoint. For example, I zoom into a specific area for review. I want to show/hide some surface type. It should be applied for the current screen area. But now it resets the view and I need to rotate and zoom trying to find my working area.
- We need multiple storey to be selected to show. For example level L2 is on top of L1. It helps to understand if the roof contour on L1 aligns with walls of L2 started from the roof.

Thank you.

**Comment by EvgenyK-SO** [comment]
For a selected surface I want to see the Zone. I expect to see a number of spaces belonging to the zone (similar to Storey). Instead I see the surface contour only:
![image](https://user-images.githubusercontent.com/39136340/52001743-2a96e980-248e-11e9-82ba-d8a0c3e49f81.png)

**Comment by theo-armour** [comment]
@EK-CEL 

See [Spider gbXML Viewer 'Maevia' R15.2]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer )

All done

**Comment by EvgenyK-SO** [comment]
Openings Problem

- 'toggle openings' doesn't keep the state. I turn it on, but when I select storeys they disappear.
- Openings should be shown for the selected storeys only, not for the entire building.

I believe openings and edges are child sub-elements of surfaces. And they should be shown only for the visible surfaces.

**Comment by EvgenyK-SO** [comment]
Zoom problem:
This button works well:
![image](https://user-images.githubusercontent.com/39136340/52057038-fecd3f80-2531-11e9-95f5-96d8b3275f04.png)

But this one is not good:
![image](https://user-images.githubusercontent.com/39136340/52057086-1c020e00-2532-11e9-85be-786fe1dedb2e.png)

**Comment by EvgenyK-SO** [comment]
Problem: When I show\hide storeys the app resets the "Show/hide by surface type" settings.

**Comment by theo-armour** [comment]
> Zoom problem:

SGV R15.4 fixes the Displays Settings > zoom all issue


> Problem: When I show\hide storeys the app resets the "Show/hide by surface type" settings.

Yup, I pointed this out in the pop-up menu help:

>> Currently has no connection with 'Show/hide by surface type' settings. Interaction and precedence is a to-be-done

Working out the way the interaction is should be is going to be tricky. And the coding is going to be fun. I think it's going to be the the latest action overrides all preceding actions. I could write this all up. But a better thing will be to build a few experiments.

 > I believe openings and edges are child sub-elements of surfaces. And they should be shown only for the visible surfaces.

Currently in R15 there is only the minimum amount of code for openings. There will be more and the above issues will be dealt with.

The only question is what is the priority for openings / data validation / sun and shadow / and a number of other features that exist in previous release that will be here one day. Any help with priorities will be appreciated.

**Comment by EvgenyK-SO** [comment]
I'd like to have the **no connection with 'Show/hide by surface type' settings** problem to be solved at first. After that the program will be fully functional and can be published for users.
The rest of the "problems" are mostly cosmetic and can be addressed when the program reaches "polishing" phase.
I guess the opening/edges "child presentation" is somewhere deep in the app core and would require significant efforts. But fixing this issue will make the app more tree-like structured and manageable.

**Comment by theo-armour** [comment]
@EK-CEL 

SGV R15.5 may provide a solution to a better the connection between

* Show/hide by surface type
* Show/hide by storeys

I will fix the openings issue at the same time as developing a future clickable openings module

**Comment by EvgenyK-SO** [comment]
Sorry , I still have a problem with surfaces and storeys. I click the following for a multistorey building model:

* [ exterior surfaces ] button
* Select LEVEL 00 from the storey list
* [InteriorWall] surface type

I expect the interior walls appeared for the selected storey only. Unfortunately the app resets the whole building.

**Comment by EvgenyK-SO** [comment]
![image](https://user-images.githubusercontent.com/39136340/52216081-73bab500-2863-11e9-9824-e6153b58efff.png)
Storey and zone buttons not working well for me. Please see a sample model, i.e. Samples1 > annapolis-md-single-family-residential-2016.xml

**Comment by theo-armour** [comment]
@EK-CEL 

Good points

Some thoughts:

**Check Revisions**
Always check that you are on latest revision. Very often you need clear the cache. Control-Shift-R should do this. Whenever I do a fix, I increment the release number so do check that we are on same page.

**Surface types and Building Storeys**
Getting the settings as you want is still very tricky. The following image was made by clicking some stoeys then clicking some types then going back and clicking some storeys.
 
![image](https://user-images.githubusercontent.com/547626/52262335-0f3e3b00-28e1-11e9-859a-fc928b15c311.png)
 
**Zones**

There are a number of issues: 

* A lot of models do not have well-defined zone
* The button for zones does not seem to be updating its text 
* Nobody has pushed me to do a better job with zones

![image](https://user-images.githubusercontent.com/547626/52263123-2e3dcc80-28e3-11e9-8261-f4f4e99719e3.png)

Let's work on this!

**Comment by EvgenyK-SO** [comment]
Thank you for the thoughts. Typically after working with a large model I open a small one, then I can load another model. I guess it should clean up the cache.

Sure the Zone issue is not crucial for core functioning, but my eyebrows go up when I see such strange behavior.  Probably I should temper my perfectionism. :) I don't understand how well-polished  should be the app to get published. Personally, I would like to have fixed the storey and surface type coordination (watch the video [here](https://screencast-o-matic.com/watch/cqnh2f35Uy)), and I can live with all other issues.

**Comment by theo-armour** [comment]
@EK-CEL 

> Typically after working with a large model I open a small one, then I can load another model. I guess it should clean up the cache.

This does not always work as wanted. often files are cached by the ISP or whatever it seems. So do check revision numbers and how to do a hard reload when playing with new releases.

> Sure the Zone issue is not crucial for core functioning, but my eyebrows go up when I see such strange behavior.

The Annapolis model - from Revit - definitely has some strange zones. Most other models - that use zones - seem to be OK. Please do point me to others of the sample models that you feel might have issues in the Viewer.

> storey and surface type coordination

Will work on it. Shade is definitely having issues. Currently storeys 'see' the surface types, but not _vice versa_. Will work on getting both to see and respond each other's states in a better way. 

I will be out exploring the countryside around the the San Francisco Bay area today and tomorrow, so no quick fixes.

**Comment by theo-armour** [comment]
@EK-CEL 

### [Spider gbXML Viewer 'Maevia' R15.6]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer )

I worked a bit on the storey. and surface type connections. The both update and check the others current status at the same time, There are many issues.

Things that help:

* Do use new reset and show all buttons
* Better first to set the surface types you want visible then second set the storeys

The interaction between all the surface types and all the levels and all the buttons you can push is complicated. It will take time and patience to work out a good work flow for suitable for most offices  

***

Show / Hide by Surface Type
* Refactor/simplify code a lot. Improve filtering for roof/shade etc. Add 'reset surfaces' and 'Show all' buttons. Add surface types and storeys connections. 

Show / Hide by Storey
* Update pop-up text
* Better connection with surface type buttons

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Tried the R15.6 update. It works better now. Unfortunately I select surface types, but they don't appear. I need to re-select the storeys I want to explore.
Still storey/surface type connection require improvements. Thank you very much for working on it!

**Comment by theo-armour** [comment]
@EK-CEL 

Thank you for the feedback. I am noticing some of these issues too. It's a very interesting set of circumstances and I am having fun tackling them. 

So let's think of some workflows that we would like to solve as a priority.

Would you like to select a group of surface type to display then check level by level and then do some editing? Or would you like to first select a level and then be able to click surface types on or off then edit?

Of course , eventually we want to do both. But in the meantime, we need to create one or two workflows that I can debug and that enable you to check things

If you could describe several steps you normally take fix a model that could really help.

***

Later on Friday: I am working on this issue now. So please wait for R15.7 before spending much time on this.

**Comment by EvgenyK-SO** [comment]
Typically I use the first scenario:** select a group of surface type to display then check level by level**.
In fact during the review I need to see how other "invisible" surface types compromise the model. For example, I choose the "Exterior Surfaces", go to a floor, and  (accidentally realizing that I need to check other surfaces)  turn on the Interior Wall surfaces (for the currently selected levels only! I don't want to reset the whole model). Then I review Interior Surfaces are not exposed. And if there is no problems I turn them off and go to the next level.

**Comment by theo-armour** [comment]
@EK-CEL 

SGV R15.7 is up

Shade is having issues. the various filter buttons have issues.

The types and storeys interaction seems to be progressing

You may need to reload - control-shift-R - several times to get all the scripts to refresh

**Comment by EvgenyK-SO** [comment]
Looks good for me.
It seems we need the Show All Storeys button.

**Comment by theo-armour** [comment]
@EK-CEL 

R15.8 ~ add (not very smart) show all storeys button

**Comment by EvgenyK-SO** [comment]
I wish the button getting smarter :)

**Comment by theo-armour** [comment]
@EK-CEL 

I think the 'show all storeys' button in SGV R15.12 is a bit smarter.

It should now be doing a better job of staying in touch with the surfaces by type settings.

**Comment by EvgenyK-SO** [comment]
Minor issue:
The app shows the "No surfaces would be visible", but they are there. It is confusing a little bit, but not important.
![image](https://user-images.githubusercontent.com/39136340/52639362-12699600-2ea2-11e9-9aa1-8d5b0bf5eb6a.png)

**Comment by EvgenyK-SO** [comment]
> I think the 'show all storeys' button in SGV R15.12 is a bit smarter.

The button works like a charm. Thank you!

**Comment by theo-armour** [comment]
@EK-CEL 

> The app shows the "No surfaces would be visible", but they are there. It is confusing a little bit, but not important.

What do you think of the behavior in Maevia 15.3?

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Sorry, I cannot find the R15.3 version.

**Comment by theo-armour** [comment]
@EK-CEL 

Oops link should have been to latest: R15.13

You can always get latest release with this link

https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/
