### ISSUE TITLE
Spider gbXML Viewer R15 Maevia: Horizontal surfaces

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/spider-gbxml-tools#19]
Roof not included in horizontal:

![image](https://user-images.githubusercontent.com/26113670/52043670-38a14480-2538-11e9-8a88-dee9e3f7863d.png)

test file if needed: 
[BHoMgbXML_gbXML.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2816452/BHoMgbXML_gbXML.zip)

**Comment by theo-armour** [comment]
fixed in r15.3

**Comment by mdengusiak** [comment]
tested, fixed and approved
thanks @theo-armour
