### ISSUE TITLE
Spider gbXML Viewer R15 Maevia: Normals need adjustment

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/spider-gbxml-tools#20]
I review and we have correct `normals `for all surfaces however here we can see traingulation so we have two surfaces from one and one is correct and second need flip. 
![image](https://user-images.githubusercontent.com/26113670/52043976-e280d100-2538-11e9-9bb0-28868305f8d8.png)

test file see Issue #19

**Comment by theo-armour** [comment]
fixed in r15.3

**Comment by mdengusiak** [comment]
tested, fixed and approved
thanks @theo-armour
