### ISSUE TITLE
Spider_gbXML_Viewer_R15.3: Can not see full model

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#23]
can not see full model when try to move left or right

![image](https://user-images.githubusercontent.com/26113670/52743857-e699fd80-2fd2-11e9-890b-bae47eec4842.png)

![image](https://user-images.githubusercontent.com/14005893/52744160-d5052580-2fd3-11e9-8675-507b61ffe975.png)

**Comment by theo-armour** [comment]
@mdengusiak 

This has to do with themes. next release has a fix.

in mean time change theme one or twice and reload should fix things

**Comment by theo-armour** [comment]
@mdengusiak 

Issues should be fixed in Maevia 15.14 and latest  https://www.ladybug.tools/spider-gbxml-tools

**Comment by mdengusiak** [comment]
tested and approved, thanks @theo-armour
