### ISSUE TITLE
Spider gbXML Viewer 'Maevia' R15.15: Add checks for Air surface types on exterior of model

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#25]
@ladybug-tools/core 

### [Spider gbXML Viewer 'Maevia' R15.15]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer )

Add beginning of working check if Air surface types are on exterior of a model

![image](https://user-images.githubusercontent.com/547626/52826254-f702b480-3074-11e9-9f70-67a760981376.png)

Air surfaces on exterior of models have had their colors changed to shades of blue

To Do
* Reset variables when loading new file
* Handle models with concavities

Note
This release adds significant new capability to a code base that is proving to be robust and fast. Time for some hard testing and a bit of marketing to start

**Comment by theo-armour** [comment]
Maevia R15.16

Highlights vertical and horizontal Air Surfaces on exterior in red and blue. Later on will help in updating to wall or roof/floor surface type,

![image](https://user-images.githubusercontent.com/547626/52885489-45bc5700-3126-11e9-9afe-2c843eb216c0.png)

**Comment by theo-armour** [comment]
Maevia R15.17

Add buttons to display only horizontal or vertical exterior air surfaces

![image](https://user-images.githubusercontent.com/547626/53144379-e52b8080-3550-11e9-8f9f-57128ff1e678.png)

Note

The user interface is becoming horribly complicated. There are as yet unknown numbers of false positives and false negatives.

Not to worry. This is a work-in-progress. There is much yet to be learned and more fails to be created.

The next steps will be adding fixing buttons that work - and even more importantly: the ability to identify external surfaces with large amounts of holes/interior courtyards and concavities. Your help will be needed here. We will need publicly shareable test case models. Some gbXML files of simple shapes - like letter of the alphabet / U, O, E, W, X & Z both in plan and section - will be much appreciated

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Thank you for progressing.
Yesterday I've got an update how our designers understand a model for **heating and cooling load calculations** (H&CLC). For some spaces, i.e. washrooms and mechanical rooms, they intentionally want to ignore exterior walls. So, they don't need automatic fix for the model.
Another problem is that generating a large gbXML model takes hours, and our process [Generate gbXML] - [Review] - [Fix Revit model] - [Repeat] takes tremendous amount of time (one cycle takes a day or two). Automatic fix doesn't work for us, as mentioned above :-(. So the best solution would be to generate a rough model and edit a few dozens of surfaces by selecting then IN GRAPHIC AREA and changing type.

It seems I mentioned it again - the multiselection is priority for us :-). But no pushing, just sharing the news.
 
 
> We will need publicly shareable test case models.

I will try to create some Revit models.

**Comment by theo-armour** [comment]
@EK-CEL 

Maevia R15.18 is up

> For some spaces, i.e. washrooms and mechanical rooms, they <the designers> intentionally want to ignore exterior walls.

All Air surfaces types showing

![image](https://user-images.githubusercontent.com/547626/53209857-b82eaa80-35f0-11e9-9782-d8d4bfb6cec4.png)


Only Internal Air surfaces showing

![image](https://user-images.githubusercontent.com/547626/53209783-77cf2c80-35f0-11e9-9da4-3f7d8f95b54e.png)


***

> So the best solution would be to generate a rough model and edit a few dozens of surfaces by selecting then IN GRAPHIC AREA and changing type.
> It seems I mentioned it again - the multiselection is priority for us :-). But no pushing, just sharing the news.

I hear you. I've added onscreen multi-selection in other projects so iyt can be done with the three.js library. And it will be added. It's just a question of when and how.

But the idea gives me nightmares. I think of the engineer clicking and clicking on model after model. And the same thing happening on all the desks in the office. And all the offices in the country. And in all the countries of the world.

The more we identify with greater clarity what the issues are with the models, the more we can automate the process of fixing models and enabling engineers to devote their time and effort in creating better, more effective designs.

**Comment by EvgenyK-SO** [comment]
> But the idea gives me nightmares.

I agree with you. We use HAP, and as a space has exterior exposures, it calculates required CFMs for heating or cooling.  Unfortunately I don't have an idea how to ignore such spaces on load calculations. But I will think about it (one click fix worth it:) ).
