### ISSUE TITLE
Sorting Storeys by elevation

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#26]
The problem is to understand which floor is upper and which is lower:
![image](https://user-images.githubusercontent.com/39136340/53119803-46862c00-351e-11e9-9b9c-9a5b82482c58.png)

It would be nice to see the Storeys in order how they appear in real life: upper floors closer to the top of the list.

Thank you.

**Comment by theo-armour** [comment]
@EK-CEL 

See Maevia R15.17

![image](https://user-images.githubusercontent.com/547626/53141058-90353d80-3543-11e9-8d16-4532f65f03e7.png)
