### ISSUE TITLE
Spider gbXML Viewer: Recenter On-screen geometry

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#27]
@EK-CEL

Please confirm this is the type of issue that needs fixing:

The issue to be fixed is that when a gbXML files includes coordinates that are six to seven digits to the left of the decimal point, then the on-screen geometry may be shifted closer to the origin so as to overcome precision errors in the display. Such transformation should have no effect on the underling gbXML data ( or should that be a choice?)

Examples of coordinates:

```
          <CartesianPoint>
            <Coordinate>604317.5</Coordinate>
            <Coordinate>4834885</Coordinate>
            <Coordinate>209.765</Coordinate>
          </CartesianPoint>
```

**Comment by EvgenyK-SO** [comment]
@theo-armour 
> Such transformation should have no effect on the underling gbXML data

Could you please clarify.

**Comment by EvgenyK-SO** [comment]
I believe it is the same issue as discussed [here](https://forums.autodesk.com/t5/revit-architecture-forum/export-gbxml-coordinates-precision/td-p/7419770).
The problem is described as *"the project coordinates are located very far from 0,0 this can lead to data corruption"*.
It happens when the Project Base Point in Revit is hundreds of miles away from the original point. For one of our project it was 5 124 406 687 mm. It seems that Revit truncates the distance to 7 digits and puts the numbers to gbXML file. Unfortunately the precision is not enough to "meet ends" for surfaces, but I am not sure that it is possible to "restore" original precision after rounding the numbers. If you can do that it would be fabulous!

**Comment by EvgenyK-SO** [comment]
Two sample files for your tests.
[ProjectBasePoint-VeryFar - R2017.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2891856/ProjectBasePoint-VeryFar.-.R2017.zip)
[ProjectBasePoint-0,0,0 - R2017.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2891857/ProjectBasePoint-0.0.0.-.R2017.zip)
![image](https://user-images.githubusercontent.com/39136340/53211480-49147e80-360f-11e9-8520-b7d17fa0bf61.png)

**Comment by theo-armour** [comment]
@EK-CEL 

No luck. Just as a simple test, using search and replace in a text editor on the XML, I truncated all the coordinates so there are only for numbers to left of decimal, Here is the result:

![image](https://user-images.githubusercontent.com/547626/53305415-33cd6900-3836-11e9-8d39-7726c1972113.png)

[ProjectBasePoint-VeryFar-truncated- R2017.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2898403/ProjectBasePoint-VeryFar-truncated-.R2017.zip)

Some of the issue with With Three.js, but most of the problems occur because the nubers in the source file are not good.

If I remember correctly, the deep down numbers that Revit uses are integers. Older programs did this to speed things on slow computers. so it looks like this type of issue - the model being far away from the origin - will have to be dealt with back in Revit.

***

> > Such transformation should have no effect on the underling gbXML data

> Could you please clarify.

The idea was that we could fix just the data that you see on the screen or we could fix the data that's in the GB XML file or we could fix both. Sadly, we can now see that none of these solutions are possible.

***

If it would be of interest, I can build a text-based utility that would test a variety of issues in gbXML files - including too-long distance from origin, lack of suitable metadata and other aspects of interest.

**Comment by EvgenyK-SO** [comment]
> a text-based utility that would test a variety of issues in gbXML files

I think it would be very helpful.
May be it is a crazy idea, but I would like to estimate how deep the gbXML model is compromised. Show the "damage degree" for every aspect. For example, depending of how far is the project from origin it can spoil geometry accuracy for 1% or 10%. If first case I can ignore the issue accept the model, with another one I either should take actions to fix the model, or consider the number in the calculation results.

**Comment by theo-armour** [comment]
@EK-CEL 

I have started 'Spider gbXML Tester', it should be ready for a first look soon.

**Comment by mdengusiak** [comment]
This is be picked up by [Spider Fixer](https://www.ladybug.tools/spider-gbxml-fixer/r2/spider-gbxml-fixer.html)
@theo-armour  to add both ways links between Maevia and Fixer,
