### ISSUE TITLE
Spider gbXML Viewer 'Maevia' R15.20: Exposed to sun error

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#28]
we have correct attributed surfaces but do not show in Maevia

![image](https://user-images.githubusercontent.com/26113670/53341536-b2dca300-3903-11e9-877b-3c718ab07c90.png)

![image](https://user-images.githubusercontent.com/26113670/53341589-dacc0680-3903-11e9-912f-f20447e4e0f7.png)

sample attached here:
[BHoMgbXML5_TAS.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2900777/BHoMgbXML5_TAS.zip)

**Comment by theo-armour** [comment]
@mdengusiak 

Fixed in Maevia R15.21

![image](https://user-images.githubusercontent.com/547626/53377848-5637b300-3918-11e9-8acc-0348c029ea76.png)

**Comment by mdengusiak** [comment]
tested and approved :)
