### ISSUE TITLE
Spider gbXML Viewer 'Maevia' R15.21: Issue with seeing surfaces data and Horizontal 

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#29]
I can not see surface properties
![image](https://user-images.githubusercontent.com/14005893/53398977-de629a80-39a2-11e9-8722-6d46ac014e08.png)

When I select Horizontal - floor is missing
![image](https://user-images.githubusercontent.com/14005893/53399043-05b96780-39a3-11e9-90e6-b0ebae7f0153.png)

See attached test file
[Rhino to BHoM Test_IES.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2904505/Rhino.to.BHoM.Test_IES.zip)

**Comment by theo-armour** [comment]
@mdengusiak 

Maevia R15.21 ~ POP/VBS > Add check for no storey name

![image](https://user-images.githubusercontent.com/547626/53450758-f9003800-39d1-11e9-97dc-a627739e4810.png)

**Comment by mdengusiak** [comment]
👍 tested and working fine
