### ISSUE TITLE
Question - Spider gbXML Viewer 'Maevia' - Priorities

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#31]
I would like to understand were the project is headed to.
Previously the target was to fix exterior surfaces, and more specific: convert Air surfaces to Exterior walls and Roofs. Now all the related issues are closed, but the target is not achieved yet:

* Automatic fix is postponed.
* There is no other way to edit surface type.

The requested workflow #15  is not finished. Parser and level&sufraces work perfectly (thank you!). But still we cannot change the surface type.
Can we have editing surfaces (multi-selection is desirable) working?

**Comment by theo-armour** [comment]
@EK-CEL 

Thank you for creating this issue. I think misread some of the texts in previous messages and became confused about things.

> convert Air surfaces to Exterior walls and Roofs.

This workflow I understand and can do.

I will also work on identifying and fixing any interior surface type found on the exterior of the model. Also any surfaces that should be shade.

The initial releases may continue to require you to push buttons in a certain order. This is bothersome but really helps me with testing. The goal of the final release is click one button to identify/highlight mis-typed surfaces. If all are OK, click another button to make the changes. 

The first step will be to write the algorithms that identify and confirm the surfaces that need updating. 

Once we agree that the algorithm works on a good number of test models, the second step will be to update the XML data withe the correct new surface type.

Does that sound OK?

**Comment by EvgenyK-SO** [comment]
> Does that sound OK?

Absolutely! Thank you.

**Comment by mdengusiak** [comment]
great...and closing this now to get all under control again :)
