### ISSUE TITLE
Multiple Objects Interactive Selection Prototype

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#32]
@EK-CEL @mdengusiak 

### [multiple objects interactive selection](  https://www.ladybug.tools/spider/cookbook/multiple-objects-edit/multiple-objects-interactive-selection.html)

Your thoughts, comments suggestions appreciated.

**Comment by mdengusiak** [comment]
@theo-armour  this is great...
1. would be possible to have one more option to `IsolateSelected ` and then `ShowAll ` but keep selection so we can revert back to all and keep selecting?

**Comment by EvgenyK-SO** [comment]
Feature request:
Center of selection is a center for orbit and zoom.

**Comment by EvgenyK-SO** [comment]
Let's say we have a situation:
The view field is full of objects, i.e looking too close to building.
I am in selection mode.
I want to orbit the view.
I left-click and move mouse.
I expect the view rotation.
Yes, the view is rotating. The problem is that I have the element selected/unselected.
Is it possible to recognize mouse movement with pressed button? If so, don't select/unselect the element under cursor.

**Comment by EK-CEL** [comment]
Why picking elements works on clicking any mouse button: left, right, and wheel?
I guess it should work with left mouse only.

**Comment by EK-CEL** [comment]
We need window selection.

**Comment by EK-CEL** [comment]
It would be nice to have a section "Navigation and Selection" and buttons under it `Revit like`, `AutoCAD like`, etc.
It relates rather to Tree.js core. But I think it should be there.

**Comment by mdengusiak** [comment]
@EK-CEL 
one idea to include... lots of interesting comment but please have a think from more abstract perspective not software but browser. 
ie... imagine we can run this via Tablet ie Ipad and still can achieve all these task..... so this solutions need to be generic

**Comment by EvgenyK-SO** [comment]
> so this solutions need to be generic

Agree. Although I think that productivity is higher on a desktop system. And if people can use the same habits switching between applications it would be more productive.

**Comment by EvgenyK-SO** [comment]
@theo-armour @mdengusiak 
I can identify the feature requests like this:

GENERIC 
---
* Make selection with left mouse button only
* Orbit/Pan/Zoom without selecting/unselecting element under cursor
* Orbit/Zoom on center of selection

DESKTOP 
---
* `Navigation and Selection` section with buttons under it `Revit like`, `AutoCAD like`, etc.
* Window selection.

**Comment by mdengusiak** [comment]
ok...

**IsolateSelected**
![image](https://user-images.githubusercontent.com/14005893/56163889-6cccc300-5fc7-11e9-9d68-c79b4a08d0ec.png)

**ShowAll**
![image](https://user-images.githubusercontent.com/14005893/56163945-8bcb5500-5fc7-11e9-8c2d-6497cf20deb7.png)


**Center of selection is a center for orbit and zoom.**
select element IsolateSelected then ShowAll, it will rotate among new center for orbit

@theo-armour 
I think most of issues are not working, can we adjust mouse button?

**Comment by theo-armour** [comment]
@EK-CEL 

Mevia R15.1.0 << new numbering system

> Make selection with left mouse button only

Done

**Comment by EvgenyK-SO** [comment]
@mdengusiak 
> select element IsolateSelected then ShowAll, it will rotate among new center for orbit

Thank you for the idea! Clicking the ![image](https://user-images.githubusercontent.com/39136340/56210162-345ad280-6023-11e9-88c5-089e09b0c79f.png) button works exactly as I expect, with two exclusions: it should be no zoom and no button. Selected elements should instantly define the centroid.

**Comment by michaldengusiak** [comment]
yes... we need to find a way  to get some workarounds sometimes... lets see what is possible

**Comment by theo-armour** [comment]
see 15.1.1

**Comment by mdengusiak** [comment]
ok this works good now...

we select vie left click

we set up center by clicking twice on surface
![image](https://user-images.githubusercontent.com/14005893/56319646-2fe50580-615a-11e9-9ff0-c48e1517e83b.png)

once surface is selected we can move with right click or keeping mouse over selected surface rotate
thanks

**Comment by EvgenyK-SO** [comment]
@mdengusiak 
> we set up center by clicking twice on surface

I would like to have more ;-)

Unfortunately the double click resets the whole scene: https://autode.sk/2VPrdY5
It is not good. I want to reset back to my storey, and keep my visibility settings when I review surfaced floor-by-floor (it is implemented by @theo-armour ).

**Comment by theo-armour** [comment]
@EK-CEL @mdengusiak 

> we set up center by clicking twice on surface

More accurate text:

Click the surface button in pop-up menu to isolate the currently selected surface and recenter the camera target to the center of the selected surface

Click the surface button again to view all the surfaces - without recentering the camera target

Click 'Zoom all' to reset the camera target to the center of the entire model


***

maevia r15.1.2
B - Pop-up shows space name 
B - Prevent middle button from updating pop-up

**Comment by EvgenyK-SO** [comment]
@theo-armour @mdengusiak 
How about this edition: 
Click the surface button again to view all the surfaces *keeping the camera center on the surface*.

**Comment by theo-armour** [comment]
@EK-CEL 

yes, that's even better text.

thank you for the video - interesting use of a product made by my former employer. ;-)

How is the functionality of this way of dealing with surfaces beginning to feel?

**Comment by EvgenyK-SO** [comment]
@theo-armour 
former employer - what feelling do you get - hate or proud? ;)

-----
My feellings about the surfaces are pleasant. Thank you for improvements. 
Only one significant request  left: ''Orbit without selecting/unselecting element under cursor''. I am not sure it can be done, but it would be great!
