### ISSUE TITLE
Spider gbXML Viewer 'Maevia' R15.23: Not possible to cut section

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#34]
Unable to cut section via my building
![image](https://user-images.githubusercontent.com/14005893/53600585-d15fca00-3ba1-11e9-9d06-85435ecfa39a.png)

see test file in #33

**Comment by theo-armour** [comment]
@mdengusiak 

Should work better in Maevia R15.25

**Comment by mdengusiak** [comment]
tested and approved thanks @theo-armour
