### ISSUE TITLE
New Script: Spider gbXML Tester R1.4

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#39]
@ladybug-tools/core 

![image](https://user-images.githubusercontent.com/547626/54252045-9d23cc00-4506-11e9-87c6-5b7df14a17c5.png)

## Bookmark this link: [Spider gbXML Tester]( https://www.ladybug.tools/spider-gbxml-tools/sandbox/spider-gbxml-tester/ )
* https://www.ladybug.tools/spider-gbxml-tools/sandbox/spider-gbxml-tester/ 

## Concept

Many of the issues to be found in parsing gbXML files are clerical matters that can found using simple text search routines - full 3D viewing is not needed and may actually slow things down. In future revisions new utilities will add replace capability so that issues can be fixed and saved.

* Run basic checks on gbXML files and identify & report errors
* The script is still at an early stage. Many more checks can be added.

## To Do / Wish List

* 2019-03-12 ~ Add as many tests currently in Spider gbXML Viewer as possible that do not require 3D
* 2019-03-12 ~ Add fixing the issues where possible
* 2019-03-12 ~ Add check for opening vertices greater then four
* 2019-03-12 ~ Add check for openings larger or outside their parent surface

## Issues

* 2019-03-12 ~ In some workflows an Air surface type with duplicate adjacent spaces acceptable. You should be able to adjust the settings so an error is not issued.

### 2019-03-12 ~ Theo

R1.2
* Looking good
* Most future change log updates will be available from the pop-up menu

### 2019-02-26 ~ Theo

* First commit

**Comment by theo-armour** [comment]
@EK-CEL @mdengusiak 
![image](https://user-images.githubusercontent.com/547626/54471806-82f32380-477c-11e9-9feb-bdd176e58b30.png)



### [Spider gbXML Tester R1.3]( https://www.ladybug.tools/spider-gbxml-tools/sandbox/spider-gbxml-tester )

* Add details and function to add add the details to divContents
* Code cleanup
* Run through jsHint

It's a lot easier to build tests here than in the 3D viewer.

* There is no need to fit into an existing UI
* There is no need to make the changes visible in the 3D model

The current effort points to a change of direction regarding the way the Viewer is developed. The viewer is currently a viewer and a fixer/editor. The way things seem to be going is that the tester should become the fixer for all testing that does not require 3D and 3D features such as ray-casting. And it currently feels like this is a doable proposition. Almost all fixes should be available with a single click. Occasionally there might be fixes where you have to choose from a list of items.

For example, let us say that you typed in an invalid surface type in your CAD program. We can let you select a valid surface type from the list of fifteen valid types. But then, we could see that your surface has a tilt of 90 degrees and it has an opening that is raised off the bottom of the surface and we can see that exposedToSun is set to true. Therefore we can pre-select 'ExteriorWall' and you can fix the error with a single click.

With some hard-thinking all of the text-based errors should be fixable in the fixer. This may mean that the viewer may more easily become a better viewer with more features being added more quickly.

Another benefit is that it will be easier to run a text-based fixer script with Node.js on a server and verify many files in a batch run

**Comment by theo-armour** [comment]
@mdengusiak @EK-CEL

![image](https://user-images.githubusercontent.com/547626/54578127-cbe4eb00-49bb-11e9-846e-e7a24e9da070.png)

### [Spider gbXML Tester R1.4]( https://www.ladybug.tools/spider-gbxml-tools/sandbox/spider-gbxml-tester/ )

* Add full details for each surface
* Open and close details depending on errors found
* Display number of errors found in summary
* Add beginning of delete and update buttons

Fingers crossed: in the next few release you will be fixing gbXML files with just a few clicks

**Comment by mdengusiak** [comment]
ok fixer in now set up here as spider-gbxml-fixer https://www.ladybug.tools/spider-gbxml-fixer/
