### ISSUE TITLE
Right side toggle doesn't work when no surface is selected

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/spider-gbxml-tools#40]
I was checking out the latest version of the gbxml-viewer (https://www.ladybug.tools/spider/gbxml-viewer/r14/gv-cor-core/gv-cor.html) an realized when there is no surface selected the <s>button</s> toggle on right side doesn't do anything. Should it be hidden at scenarios like this?

![image](https://user-images.githubusercontent.com/2915573/54477969-971e3b80-47e3-11e9-99b8-8b4d8594e155.png)

1. <s>I know it is not a button but I don't know what should I call it!</s> Toggle!
2. I tested it in FireFox 65.0.2 on Windows 10.

**Comment by mdengusiak** [comment]
@mostaphaRoudsari  I normally use [R12 ](http://www.ladybug.tools/spider/gbxml-viewer/r12/gv-app/gv-app.html)or [R15](https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/r15/spider-gbxml-viewer15.html#https://www.ladybug.tools/spider/gbxml-sample-files/bristol-clifton-downs-fixed.xml)

 however this what we call `right hand menu ` is tod hide selection detail
I tested on R14 and you need to select surface to show detail and click  to hide... it works fine on Chrome
![image](https://user-images.githubusercontent.com/26113670/54479492-298b0300-4815-11e9-890a-e03e011396a6.png)

![image](https://user-images.githubusercontent.com/26113670/54479495-34de2e80-4815-11e9-8bed-c1212cd681e2.png)

**Comment by mostaphaRoudsari** [comment]
> I tested on R14 and you need to select surface to show detail and click to hide

That was my point. If it doesn't have a functionality when a surface is not selected then I would say it should be hidden or grayed out until one selects a surface.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Agreed. the button should be at least grayed out when it is not available.

But pushing even further: having two sliding menus on an app that is viewable on a phone or tablet is too tricky.

R15 does away with the slider button and the pop-up menu just opens and closes. R15 has , however, a lot of other work-in-progress issues on a phone BTW,

**Comment by mdengusiak** [comment]
moved to correct repo

**Comment by mostaphaRoudsari** [comment]
Hi @mdengusiak, Just in case you didn't know you can transfer issues between repositories:

![image](https://user-images.githubusercontent.com/2915573/56168796-3d5b8d80-5faa-11e9-8880-f56e17f358fe.png)
