### ISSUE TITLE
Spider gbXML Viewer V 0.16.0

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#42]
@mdengusiak 

## [Spider gbXML Viewer V 0.16.0]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/dev/ )

![image](https://user-images.githubusercontent.com/547626/59481208-35886000-8e18-11e9-9f5a-7f5eb0c0a96d.png)

* First commit
* Uses same content management scripts as Atrax
* Switch to semver version numbers
* Has all R15 features except editing ( coming soon)
* Adds new feature: Show all surfaces sharing vertices with the currently selected surface

**Comment by theo-armour** [comment]
V 0.16.01

[Spider gbXML Viewer 'Maevia' ]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-16-01/viewer-view/spider-gbxml-viewer-view.html )

[Spider gbXML Fixer 'Atrax']( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-16-01/viewer-fixer/spider-gbxml-viewer-fixer.html )

**Comment by michaldengusiak** [comment]
@theo-armour  this is great
