### ISSUE TITLE
Spider gbXML Viewer: Visualise Opening

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/spider-gbxml-tools#43]
Allow Opening selection and display data  same as for Surfaces so something like:

Selected Openings Attributes
openingType : NonSlidingDoor
id: aim13150
CADObjectId: Basic Roof: SIM_EXT_SLD_Roof DA01 [929372]
Name: T-RF_102-E-R-495

Also geoemtry data
Width
Height
Number of points
Area

**Comment by theo-armour** [comment]
@michaldengusiak 

[Spider gbXML Viewer 'Maevia' ]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-16-01/viewer-view/spider-gbxml-viewer-view.html )

[Spider gbXML Fixer 'Atrax']( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-16-01/viewer-fixer/spider-gbxml-viewer-fixer.html )

**Comment by michaldengusiak** [comment]
@theo-armour 
this is great
can we add ti CAD Object ID groups also Openings, groups and without element ID

![image](https://user-images.githubusercontent.com/26113670/60458535-cba0f080-9c36-11e9-9862-58973a3743d9.png)

**Comment by theo-armour** [comment]
@mdengusiak 

> can we add ti CAD Object ID groups also Openings, groups and without element ID

Please expand and clarify

**Comment by michaldengusiak** [comment]
@theo-armour  so as discussed new item 
`CAD object id groups Openings`

**Comment by michaldengusiak** [comment]
this is now implemented in  Spider gbXML Viewer 'Maevia' 0.17.05-0
![image](https://user-images.githubusercontent.com/26113670/67365073-cdd1e680-f568-11e9-857f-b5a26f4fe26b.png)
