### ISSUE TITLE
Spider gbXML Viewer: Construction Attributes

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/spider-gbxml-tools#44]
Display Construction information and option for detail items Materials

**Comment by theo-armour** [comment]
@michaldengusiak 

[Spider gbXML Viewer 'Maevia' ]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-16-01/viewer-view/spider-gbxml-viewer-view.html )

[Spider gbXML Fixer 'Atrax']( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-16-01/viewer-fixer/spider-gbxml-viewer-fixer.html )

**Comment by theo-armour** [comment]
@michaldengusiak 

![image](https://user-images.githubusercontent.com/547626/60167009-0f1ed900-97b7-11e9-8e52-6318cd92a18e.png)

**Comment by michaldengusiak** [comment]
@theo-armour  looks great
can we display construction by name not ID, and CADObjectID as well thanks

**Comment by michaldengusiak** [comment]
@theo-armour  perfect!
![image](https://user-images.githubusercontent.com/26113670/60458660-191d5d80-9c37-11e9-92e1-a85253a5fab8.png)
