### ISSUE TITLE
Spider gbXML Viewer 'Maevia' v0.17.02

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-tools#47]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/62670316-aabf6f80-b947-11e9-84b0-e6d75ed99ae2.png)

This is a significant update for the following reasons (plus a few more):

1. I am, at last, not unhappy with the code. It's not great code. Perhaps more importantly it's not such bad code either.

2. I am not unhappy with the mission and vision. It's not so much about helping humans find errors. It's now more about fixing the errors for the humans.

3. I am not unhappy with the process for increasing awareness of the project. It's not so much about imitating commercial projects and advertising agencies. It's about sharing metrics and standards for open source capabilities and solutions.

And given all this un-unhappiness, I am very happy to tackle the future of this project wherever you help me take it.

Things for you to look at include:

### [Updated Read Me]( https://www.ladybug.tools/spider-gbxml-tools/#spider-gbxml-viewer/README.md )

* Written for people who know nothing about the project, have dropped in almost by accident
* Target reader: a non-technical person, a middle manager or a student

### [Spider gbXML Viewer compliance with ISO 245010 ~ System and software quality models]( https://www.ladybug.tools/spider-gbxml-tools/index.html#spider-gbxml-viewer/spider-gbxml-viewer-iso-25010-compliance.md )

* By clarifying project priorities and converting abstract priorities to measurable values this document develops a common and shareable understanding of the objectives and capabilities of the Spider gbXML Viewer project.

### [Spider gbXML Viewer v0.17.02]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/ )

* Simpler,faster and easier to use
* Fixes the gbXML errors for you
* Written in plain vanilla JavaScript

**Comment by EvgenyK-SO** [comment]
@theo

Don't worry, be happy! :-)

P.S. Thank you for your restless efforts.

**Comment by michaldengusiak** [comment]
Spider gbXML Viewer 'Maevia' v0.17.05 release as stable version :)

### [Spider gbXML Viewer v0.17.05]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/ )
