### ISSUE TITLE
Reset Exploded problem

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#48]
I cannot bring exploded model back to "assembled". Here is the video:
https://autode.sk/2YLUp7T

**Comment by theo-armour** [comment]
@EK-CEL 

Thanks for the heads up. Things should be much better in [0.17.02-1sgv](https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer)

![image](https://user-images.githubusercontent.com/547626/62998647-06df3380-be21-11e9-9112-129120e4b1ad.png)

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Thank you for fixing it.
One more minor issue. Please try the steps:
1. Explode by Storeys 2
2. Plus, Plus, Plus
3. Explode by Storeys 2
4. Minus, Minus, Minus.

Theoretically the steps should bring the model back to a nice assembly. Unfortunately the result doesn't look nice.

**Comment by EvgenyK-SO** [comment]
BTH. You have nice icons for the model review buttons, I don't. 
![image](https://user-images.githubusercontent.com/39136340/63022766-96143780-be71-11e9-94e5-bbc2ceca3c31.png)

Maybe because of Chrome?

**Comment by EvgenyK-SO** [comment]
I borrowed the "Explode" icon from AutoCAD.
![image](https://user-images.githubusercontent.com/39136340/63022345-b1cb0e00-be70-11e9-8da1-2967bc931210.png)
Don't you want to use it?

**Comment by michaldengusiak** [comment]
@EK-CEL  I also use Chrome and looks fine, interesting...
you can `explode `and then `reset `and works fine

![image](https://user-images.githubusercontent.com/26113670/63023494-2451e300-be9d-11e9-92c2-a84bb8c8ddb5.png)

![image](https://user-images.githubusercontent.com/26113670/63023395-f5d40800-be9c-11e9-9355-47d19fa56321.png)


![image](https://user-images.githubusercontent.com/26113670/63023494-2451e300-be9d-11e9-92c2-a84bb8c8ddb5.png)

**Comment by EvgenyK-SO** [comment]
> you can explode and then reset and works fine

Thank you. I know that. That's why I marked the issue as minor. ;-)

**Comment by EvgenyK-SO** [comment]
Good enough to be closed.
