### ISSUE TITLE
Fix absent materials

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#49]
Revit has its own considerations what information put into the exported gbXML file. And quite often it misses surface materials. The main reason for that is that Revit required to have thermal properties for materials. If they are not defined then the material doesn't appear in the generated gbXML file. We can push architect for thermal properties input, but there is no guarantee they follow our requirements. That's why we should be able to assign a default material to external surfaces (Walls, Raised Floors, Roofs, Windows, and Doors) which miss a material (constructionIdRef).
![image](https://user-images.githubusercontent.com/39136340/63373148-66739c80-c355-11e9-890f-73ff5ad8ec20.png)
I consider that issue as a critical problem. It would be nice to have it fixed automatically. Please find sample files attached.
[Stacked_Wall_For_TakeOff-M17.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/3522034/Stacked_Wall_For_TakeOff-M17.zip)
[Stacked_Wall_For_TakeOff-M17 #1.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/3522035/Stacked_Wall_For_TakeOff-M17.1.zip)

Thank you.

**Comment by theo-armour** [comment]
@EK-CEL 

Agreed. This is a big issue.

If nothing else, lack of construction material information prevents most gbXML files from being accepted by OpenStudio prior to the creation of a report. This is a high-priority new feature.

I plan to start adding construction data after having added some of the 3D fixers - perhaps starting by next week.

What will be need is a good set of default materials for ft-in and metric projects. Later on we can get more sophisticated and adjust the data according to lat/lon and data from the closest EPW file.

If you have some good ideas for default constructions, materials and layers, please do share.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey has a default construction library that should be helpful here.

**Comment by EvgenyK-SO** [comment]
Revit has XML file with default constructions.
[Constructions.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/3525366/Constructions.zip)

**Comment by EvgenyK-SO** [comment]
Revit suggests the following default values:
Metric:
![image](https://user-images.githubusercontent.com/39136340/63436317-7a230f80-c3f6-11e9-80ef-f2541b3048fc.png)

Imperial:
![image](https://user-images.githubusercontent.com/39136340/63436758-41376a80-c3f7-11e9-90de-46fbf97a66ac.png)

@theo-armour 
You are right the default values depend of the project location.

**Comment by theo-armour** [comment]
@EK-CEL @michaldengusiak 

See also #35 

I should have a bit of a demo going next week. It will be a basic routine that does a search and replace to the gbXML file. I will keep adding sufficient to the file until it can be used to generate an OpenStudio report without error. Once we have a dummy file working we can add country by country versions.

I will start by using this file to add the construction data:

https://github.com/ladybug-tools/spider-gbxml-tools/blob/master/assets/construction-defaults.xml

here are the first few lines

```

  <Construction id="Air">
    <Absorptance unit="Fraction" type="ExtIR">0</Absorptance>
    <LayerId layerIdRef="layer" />
    <Name>Air</Name>
    <Roughness value="Rough" />
    <U-value unit="WPerSquareMeterK">0.999999</U-value>
  </Construction>
  <Construction id="Ceiling">
    <Absorptance unit="Fraction" type="ExtIR">0</Absorptance>
    <LayerId layerIdRef="layer" />
    <Name>Ceiling</Name>
    <Roughness value="Rough" />
    <U-value unit="WPerSquareMeterK">0.999999</U-value>
  </Construction>
  <Construction id="EmbeddedColumn">
    <Absorptance unit="Fraction" type="ExtIR">0</Absorptance>
    <LayerId layerIdRef="layer" />
    <Name>Embedded Column</Name>
    <Roughness value="Rough" />
    <U-value unit="WPerSquareMeterK">0.999999</U-value>
  </Construction>

```

**Comment by theo-armour** [comment]
@EK-CEL @michaldengusiak

Bookmark this link:
## https://www.ladybug.tools/spider-gbxml-fixer/

Two fairly complex files seem to be making the trip to OpenStudio

* [berlin-office-1-1k-surfaces.zip]( https://www.ladybug.tools/spider-gbxml-fixer/v-0-05-0/spider-gbxml-fixer-dev.html#https://cdn.jsdelivr.net/gh/ladybug-tools/spider@master/gbxml-sample-files/zip/berlin-office-1-1k-surfaces.zip )
* [winchester-school-560-surfaces.zip]( https://www.ladybug.tools/spider-gbxml-fixer/v-0-05-0/spider-gbxml-fixer-dev.html#https://cdn.jsdelivr.net/gh/ladybug-tools/spider@master/gbxml-sample-files/zip/winchester-school-560-surfaces.zip )

It can tale a while for results to appear with large files.

Also very simple files with just a space or two and few windows seem to make the trip.

It's a start...

**Comment by michaldengusiak** [comment]
@theo-armour 
something does not look right in xml, please have a look
![image](https://user-images.githubusercontent.com/26113670/63753907-e052db00-c8ab-11e9-89e6-a3e1421204dd.png)

**Comment by theo-armour** [comment]
@michaldengusiak 

Looks like a ZIP file to me

Try save to text

**Comment by michaldengusiak** [comment]
in that case please change the extension on save..so it is .zip not .xml

**Comment by theo-armour** [comment]
fixed

**Comment by michaldengusiak** [comment]
@theo-armour  now better
but please review the first-line... I guess this might be causing the issue ... I see these warnings and can not see the building
![image](https://user-images.githubusercontent.com/26113670/63759323-311b0180-c8b5-11e9-94cd-696b0afcf7e0.png)

**Comment by theo-armour** [comment]
@michaldengusiak 

I get those errors as well. Probably an extra ">" somewhere.

And I am not looking at the building. I am currently just testing to see if the HTML report is created

And I have seen a number of successes

**Comment by theo-armour** [comment]
@michaldengusiak 

Spider gbXML Fixer 'Atrax' 0.05.01 should have fixed the errors issues. It looks like a utf-16 to ust-8 thing

**Comment by theo-armour** [comment]
@chriswmackey 

Mostapha reminded me: 

> @chriswmackey has a default construction library that should be helpful here.

But I can't seem to find the details. Can you help?

**Comment by chriswmackey** [comment]
@theo-armour ,

Thanks for bringing me in the loop here and, yes, we recently finished putting together a default material and construction library for all common surface types and boundary conditions.  I think it will serve your purposes well here.  [Here are all of the materials and constructions in IDF format](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/lib/idf/constructions/default.idf).  If it's easier, you can also find [a Python dictionary with all material properties here](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/lib/materials.py#L10-L45) as well as [a Python dictionary with all of the material layers for the construction here](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/lib/constructions.py#L9-L38)

[This dictionary here shows good logic for how they can be applied based on surface type and boundary condition](https://github.com/ladybug-tools-in2/energy-model-schema/blob/develop/app/models/samples/json/model_single_zone_tiny_house.json#L11-L45) and this logic generally follows how OpenStudio structures its ConstructionSet objects.

Another benefit of these materials is that we have chosen their solar and visible reflectances / transmittances to align with standard properties of Radiance materials, meaning that its easier to coordinate the energy model with radiance simulations.

The thermal properties of the materials are not in line with a particular building code or climate zone because 1. we didn't want to show favoritism to any particular climate and 2. we ultimately would like people to change these default materials to suit their building code or performance targets.  However, all of the numbers are realistic representations of "typical" constructions for a building constructed in the last few decade. They are sourced either from the OpenStudio standards gem or the LBNL WINDOW International Glazing Database.

**Comment by michaldengusiak** [comment]
@theo-armour 
ok tested again...

1. please adjust text
![image](https://user-images.githubusercontent.com/26113670/63916630-b7a81e00-ca30-11e9-8afb-b8d942a6d86c.png)
2. I imported this file into openstudio and still have the same warning on import
![image](https://user-images.githubusercontent.com/26113670/63916683-d27a9280-ca30-11e9-9537-ee3617555e91.png)
I believe this is related to same problem
![image](https://user-images.githubusercontent.com/26113670/63916714-e4f4cc00-ca30-11e9-9708-d602c4b29254.png)

3. tested on zip and then the same issue with first line
![image](https://user-images.githubusercontent.com/26113670/63916788-05248b00-ca31-11e9-811d-b994004d8003.png)

**Comment by theo-armour** [comment]
@michaldengusiak 

Spider gbXML Fixer 'Atrax' v0.05.02 is up

https://www.ladybug.tools/spider-gbxml-fixer

Some fairly complex files seem to be making the trip to OpenStudio

* [berlin-office-1-1k-surfaces.zip]( https://www.ladybug.tools/spider-gbxml-fixer/v-0-05-0/spider-gbxml-fixer-dev.html#https://cdn.jsdelivr.net/gh/ladybug-tools/spider@master/gbxml-sample-files/zip/berlin-office-1-1k-surfaces.zip )
* [winchester-school-560-surfaces.zip]( https://www.ladybug.tools/spider-gbxml-fixer/v-0-05-0/spider-gbxml-fixer-dev.html#https://cdn.jsdelivr.net/gh/ladybug-tools/spider@master/gbxml-sample-files/zip/winchester-school-560-surfaces.zip )
* [bristol-clifton-downs-broken.xml]( https://www.ladybug.tools/spider-gbxml-fixer/v-0-05-0/spider-gbxml-fixer-dev.html#https://cdn.jsdelivr.net/gh/ladybug-tools/spider@master/gbxml-sample-files/bristol-clifton-downs-broken.xml )
* london-office.xml
* london-royal-arsenal-woolwich.xml

It can take a while for results to appear with large files.

![image](https://user-images.githubusercontent.com/547626/63921891-7b58cb80-c9f8-11e9-8a74-a8f818cabe3f.png)

![image](https://user-images.githubusercontent.com/547626/63921962-988d9a00-c9f8-11e9-8970-46262be04bae.png)

**Comment by michaldengusiak** [comment]
@theo-armour  this is strange

1. thanks for the fix - done
![image](https://user-images.githubusercontent.com/26113670/63922431-98af8900-ca3c-11e9-887e-840011769a63.png)

2. however when I export file 
I still see an issue with first-line... and does not import 
![image](https://user-images.githubusercontent.com/26113670/63922453-a1a05a80-ca3c-11e9-8b12-52c3f9d35992.png)

i reviewd files:
gbXML from Revit
![image](https://user-images.githubusercontent.com/26113670/63922526-c3014680-ca3c-11e9-805f-1ff44cf53d5a.png)

gbXML from BHoM
![image](https://user-images.githubusercontent.com/26113670/63922562-d4e2e980-ca3c-11e9-973f-e5cda83051cb.png)

when I replaced the first line with
`<?xml version="1.0" encoding="utf-8"?>`
it works

![image](https://user-images.githubusercontent.com/26113670/63923635-c695cd00-ca3e-11e9-8541-cc4edbee39d9.png)


also, I tested into TAS and here is list of warnings
![image](https://user-images.githubusercontent.com/26113670/63923216-0d36f780-ca3e-11e9-8d93-5d3ec22210ea.png)

3. also names are missing, try to call the construction as building element name
![image](https://user-images.githubusercontent.com/26113670/63923576-af56df80-ca3e-11e9-8720-13fb79270e12.png)

so try to set for Construction `<Name>` actually building element name

we have this
```
<Construction id="ExteriorWall">
<U-value unit="WPerSquareMeterK">0</U-value>
<Absorptance unit="Fraction" type="ExtIR">0</Absorptance>
<Roughness value="Rough" />
<LayerId layerIdRef="layer-exterior-wall" />
<Name>Exterior Wall</Name>
</Construction>
```

should be this
```
<Construction id="ExteriorWall">
<U-value unit="WPerSquareMeterK">0</U-value>
<Absorptance unit="Fraction" type="ExtIR">0</Absorptance>
<Roughness value="Rough" />
<LayerId layerIdRef="layer-exterior-wall" />
<Name>Basic Wall: SIM_EXT_SLD AHU</Name>
</Construction>
```
so we have recognized
![image](https://user-images.githubusercontent.com/26113670/63923997-6b180f00-ca3f-11e9-9f10-66f1aab7394a.png)

here were to take it from
![image](https://user-images.githubusercontent.com/26113670/63925549-2f327900-ca42-11e9-8b76-55b28edc9baf.png)

**Comment by theo-armour** [comment]
@michaldengusiak 

>> 2. I imported this file into openstudio and still have the same warning on import

Spider gbXML Fixer 'Atrax' v0.05.3

If found, deletes mystery character at first position in file

Bertin_Office.xml - 12MB

![image](https://user-images.githubusercontent.com/547626/63983322-0c708680-ca7b-11e9-87a4-381cc0e77daa.png)

![image](https://user-images.githubusercontent.com/547626/63983095-0d54e880-ca7a-11e9-86e8-dd29df2408ea.png)

>> 3. also names are missing, try to call the construction as building element name (CADObjectId )

Can you verify that this solution would work across a variety of gbXML file creators and across the workflow of a variety of organizations in various countries

Another way f doing it might be to offer a variety of solutions, and you pick the one you need for your current project

***

Also, new issues should probably be sent here:

https://github.com/ladybug-tools/spider-gbxml-fixer/issues

**Comment by michaldengusiak** [comment]
@theo-armour 
ok I run details test and could not get it to work... here is a simple example
current construction inserting fail...
attached file..

```
Program Version,EnergyPlus, Version 9.1.0-08d2e308bb, YMD=2019.09.06 13:50,
   ** Severe  ** <root>[Construction][Ceiling] - Missing required property 'outside_layer'.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=<root>[Construction][Ceiling] - Missing required property 'outside_layer'.
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.24sec

```

![image](https://user-images.githubusercontent.com/26113670/64429301-8f15c900-d0ad-11e9-9916-2b5e1a4022b8.png)

![image](https://user-images.githubusercontent.com/26113670/64429384-cdab8380-d0ad-11e9-808f-bc2dd10a8f2d.png)


[Building7.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/3583972/Building7.zip)

**Comment by michaldengusiak** [comment]
template with the material are now added and works fine
we can start populating standard construction for different countries or climates 

I am close to solving this... few more cases to test
https://discourse.ladybug.tools/t/construction-layers-gas-materials-gbxml-help-needed/7304

**Comment by EvgenyK-SO** [comment]
Just curious - would it ever possible to change material R values with gbXML viewer?

**Comment by theo-armour** [comment]
@EK-CEL 

Of course.

Do you have a standard set of R values that could be applied?

And maybe now this feature is mostly working, you could start a new issue about this and: can we close this issue since it takes so long to get down to here?

**Comment by michaldengusiak** [comment]
Yes, idea is that we have now template to set up standard constructions, layers and materials. So you can generate you own document and apply standard data for your region, specific standard, project or favourite settings. 
this can be chosen here and added to gbXML,
please share your values and source so we can expand the standard selection.
![image](https://user-images.githubusercontent.com/26113670/67364613-cf4edf00-f567-11e9-9654-fa84795187f5.png)
Unless you just referring to adjusting R for existing materials that are already added?
I will close this and we can start a new conversation/issue as this was to fix absent materials to allow OpenStudio to run and this is now fixed
