### ISSUE TITLE
Spider gbXML Viewer 'Maevia' v0.17.04 - BiLT EUR 2019 list

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/spider-gbxml-tools#50]
- [x] spaces are missing from view
![image](https://user-images.githubusercontent.com/26113670/66812173-4eba2e00-ef2a-11e9-9201-793954b6ad54.png)

- [x] add links between all toolkits so  we can swap between tools with one click both ways
![image](https://user-images.githubusercontent.com/26113670/66812251-714c4700-ef2a-11e9-95b1-1736b2e883b0.png)

- [x] Michalina to record a new video for the current version 

- [ ] add OpenMaps (or other sources) if possible content to gbXML as Shade  surface type
https://www.openstreetmap.org/export#map=17/55.92989/-3.25679  
https://twitter.com/data_shapes/status/1130103420071960576
https://rawgit.com/ladybug-tools/spider/master/analemma3d/index.html#r20/analemma3d.html#latitude:37.8024,longitude:-122.4058,zoom:16,offsetUTC:-420

**Comment by theo-armour** [comment]
@michaldengusiak 

- [x] view

![image](https://user-images.githubusercontent.com/547626/66877091-0d953e80-ef69-11e9-96cb-91aa3d849cc4.png)


## https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/dev/

**Comment by michaldengusiak** [comment]
@theo-armour  this is great,
we just await @michalinadengusiak for the updated video,
I guess context will be larger task. 
Are we able easily extract surface coordinates from context building in order to create shade?
I will explore if I can set up BHoM, Dynamo workflow to easily add context from Maps...

**Comment by theo-armour** [comment]
@michaldengusiak 

**Stable release**
Is v0.17.)5 OK to be labeled the stable release?

**Maps etc

We have maps, terrain, sun positions and adjacent building data for any any world latitude and longitude in Analemma 3D and gbXML data in the viewers. The next step is combining the code. It's not difficult, just quite time-consuming. 

Is there anything of interest that BHoM could add?

**Comment by michaldengusiak** [comment]
@theo-armour 

1. yes, 100% we can move ver Dev 0.17.05-0 as a stable release,
2. if we have capability then no, I was just thinking about a workaround if we are unable to add shade surfaces into gbXML when saving. It is then great news

**Comment by michaldengusiak** [comment]
@theo-armour 

1. can you please adjust link
![image](https://user-images.githubusercontent.com/26113670/67145508-fcef0c00-f279-11e9-8331-d74fa8c4cb35.png)


![image](https://user-images.githubusercontent.com/26113670/67145530-332c8b80-f27a-11e9-995f-bc2a3a6c999b.png)

should be

`http://www.ladybug.tools/spider/gbxml-viewer` [link](http://www.ladybug.tools/spider/gbxml-viewer)

2. when file is opening please do not load - air at start

![image](https://user-images.githubusercontent.com/26113670/67145651-0036c780-f27b-11e9-90b2-3111e0961bb0.png)

**Comment by michalinadengusiak** [comment]
@theo-armour @michaldengusiak 
I completed my task of doing the video.
:)

**Comment by theo-armour** [comment]
Aragog link : fixed

no Air on start

Thank you, Michalina

**Comment by michaldengusiak** [comment]
ok this is great we close almost all and I will open context as a separate issue as this will be bigger task,
