### ISSUE TITLE
Colorless icons

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#52]
On your screenshots I see the nice icons:
![image](https://user-images.githubusercontent.com/39136340/67392946-72572700-f56f-11e9-83b2-a262e235733a.png)

Unfortunately they don't appear on my computer. I tried several computers in our company. They all have the same picture:
![image](https://user-images.githubusercontent.com/39136340/67393029-9581d680-f56f-11e9-9aea-ec2f5a909f49.png)

It is not a big problem. I can work with colorless icons. But it would be nice if you can fix the missing icons for this icon set.

**Comment by michaldengusiak** [comment]
@EK-CEL I had this before on my old laptop this was due to the graphic card. I have now a different one is solved.
@theo-armour Any suggestions if there is some workaround

**Comment by EvgenyK-SO** [comment]
Seems the symbols are in the page source code:
![image](https://user-images.githubusercontent.com/39136340/67398202-4c825000-f578-11e9-8327-286237dd97d8.png)

**Comment by michaldengusiak** [comment]
@EK-CEL 
not on ours
![image](https://user-images.githubusercontent.com/26113670/67398412-85cfb580-f5a2-11e9-945f-e7823d45125a.png)

**Comment by EvgenyK-SO** [comment]
How can it be?

**Comment by EvgenyK-SO** [comment]
Do you use Apple device?

**Comment by michaldengusiak** [comment]
No, I use Windows 10, 
Processor Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
NVIDIA Quadro P2000
Intel(R) UHD Graphics 630

@theo-armour  will explain this better this is due to Intel graphic card

**Comment by EvgenyK-SO** [comment]
In our office we use Windows 7 systems. I believe it causes the problem as different systems use different icons.
![image](https://user-images.githubusercontent.com/39136340/67399580-763c7680-f57a-11e9-9e6a-424ffe977820.png)

I think icons (actually unicode character table) are installed on the computer. So Windows 7 has a different file. We need using unicode characters which work for Windows 7 as well.

**Comment by EvgenyK-SO** [comment]
I found the following symbols:
☲  - for Surface types
💣  - for Exploded views

My icons look like this:
![image](https://user-images.githubusercontent.com/39136340/67403238-a1759480-f57f-11e9-8cbe-8e391f405b1d.png)


What if we would use them?

**Comment by EvgenyK-SO** [comment]
One icon on the top toolbar is also not shown on my computer:
![image](https://user-images.githubusercontent.com/39136340/67415534-346bfa00-f593-11e9-805d-2479a72a2359.png)

Can we use the symbol 🔃 ?

**Comment by EvgenyK-SO** [comment]
For the button "Show entire campus & display attributes" (for top and bottom toolbars) this symbol is used:
![image](https://user-images.githubusercontent.com/39136340/67415819-b1976f00-f593-11e9-86b1-e18c3164bd7d.png)
It rather suggests that we can search for something.

My proposition is to use just the "Home" button, which properly describes the action.
The 🏠 symbol is visible on my computer.

**Comment by EvgenyK-SO** [comment]
Currently the "door" symbol 🚪 is used for button "Show openings". It rather suggests the "Exit" action.
What if we use the ⊞ symbol for the button?

**Comment by theo-armour** [comment]
@EK-CEL 

Do you have an IT group that sets up your systems? If so, they may have limited your setup somehow?

The default icons in v0.17 show up on my W10 machine with latest Chrome, Edge and FF. Also on my Android phone and Chromebook. They are based on UTF-8. I find the icons using tools like these: https://unicode-table.com/en/sets/top-emoji/

**Comment by EvgenyK-SO** [comment]
@theo-armour 
I told our IT department about the problem. Apparently nice icons appear on W10 machines, but not on W7 ones. We spent an hour trying to install a correct Arial TTF font version on W7 machine. The latest Arial font version is 7, but W7 takes only version 5. We couldn't find a way to enforce W7 using Arial V7.

**Comment by EK-CEL** [comment]
Probably there is now reason to fight the problem. In two years there will be no W7 machines in the our business.

**Comment by EvgenyK-SO** [comment]
Probably there is now reason to fight the problem. In two years there will be no W7 machines in the  business where the Ladybug and Spider live.

@theo-armour @michaldengusiak 
Above there are my propositions to replace some icons which would be more understandable. 
If you think the changes are not reasonable please close the issue.

**Comment by theo-armour** [comment]
@EK-CEL 

It would be very easy for someone who knows a bit of JavaScript and a bit of GitHub to fork (copy) the program and change the icons (and many other aspects) to fit the needs of a specific set of users such as yourself.

Every line of code in the software I write is dedicated to the idea that students and professionals who know a lot about engineering and a little bit about programming should be able to modify and tailor the code for new - or old - uses.

 The sad thing is that I have so much fun writing the software that I do not spend enough time sharing the wisdom embedded in what I do.

***

I am a software designer. My job is to build for Windows 11 and what happens in the future. Once something is finished - punch card, modems, W7 and whatever - my best achievement is to entirely forget that the thing ever existed. If I do not forget, then I am designing for the future by looking in the rearview mirror.

***

W7 came out in 2009. Why is your organization is using ten year old tools to design the buildings of the future?

![bitmoji](https://render.bitstrips.com/v2/cpanel/c9761dd5-6a67-482a-8a24-5ed0732c4a81-5f4ac99a-b79e-4303-acc1-cf0fa75e2509-v1.png?transparent=1&palette=1&width=246) 

 BTW, the beers at the pub this evening were delicious

**Comment by EvgenyK-SO** [comment]
Starting the issue I didn't mind that the problem is in Windows version. The W7 support is officially stopped, so the Spider can "officially" refuse to do any update for it. ;-)
